### ISSUE TITLE
Permafrost

### ISSUE THREAD

**Issue by Erin-Morrison** [JGCRISummer2024/Arctic_Fox#3]
I would like to get permafrost data into my model. Here are the links from the emails. Soil-drainage data would also be awesome if possible.

[https://arcticdata.io/catalog/portals/permafrost](url)

[https://arcticdata.io/catalog/view/urn%3Auuid%3A054b4c9a-8be1-4d28-8724-5e2beb0ce4e6#urn%3Auuid%3Ace83d4c5-b4a9-43c6-9006-0fedff8ac66b](url)  Not from the emails but looked like the place to actually get the data from the previous link.

[https://essd.copernicus.org/articles/13/5127/2021/#section2](url)  First table

**Comment by bpbond** [comment]
Hi @Erin-Morrison I think the best source to use is from this paper:

Karjalainen, O., Aalto, J., Luoto, M., Westermann, S., Romanovsky, V. E., Nelson, F. E., Etzelmüller, B., and Hjort, J.: Circumpolar permafrost maps and geohazard indices for near-future infrastructure risk assessments, Sci. Data, 6, 190037, 2019. https://www.nature.com/articles/sdata201937#Sec17

It's pretty high resolution: 30 arc seconds, ~932 × 466 m at 60°N latitude. Data are provided as a GeoTIFF and should be straightforward to use:
```
class       : SpatRaster 
dimensions  : 6435, 43200, 1  (nrow, ncol, nlyr)
resolution  : 0.008333334, 0.008333334  (x, y)
extent      : -180, 180, 30, 83.625  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : PF_baseline.tif 
name        : PF_baseline 
```

I'll send you the data file via email!
